Feature/homework 7
emmaderbe/ShiftHomeworks pull request #7
Opened 2024-06-04 15:51 UTC by emmaderbe

Реализовала мобильное приложение согласно тз:
* Архитектура приложения - MVC;
* Запросы осуществляются на Unsplash (https://unsplash.com/documentation#search-photos);
* Запросы нативные;
* Реализован основной функционал приложения: получение фото по запросу, добавление фото в таблицу, загрузка фото в фоновом режиме;
* При любой ошибке пользователь получает алерт с описанием.

2024-06-11 16:16 UTC, rmaximov requested changes
Обнаружил краш на обработке ошибок в сетевом слое

Хорошая работа, используешь модификаторы доступа, есть некая архитектура, код лаконичный

2024-06-11 16:16 UTC, rmaximov commented on homework7/homework7/App/AppDelegate.swift
> +    }
пустой метод затисался

2024-06-11 16:16 UTC, rmaximov commented on homework7/homework7/Application/AppDelegate.swift
> +    func application(_ application: UIApplication, didDiscardSceneSessions sceneSessions: Set<UISceneSession>) {
и тут пустой

2024-06-11 16:16 UTC, rmaximov commented on homework7/homework7/Enums/ConstEnum.swift
> +enum ConstEnum {
minor: можно назвать проще Constants

2024-06-11 16:16 UTC, rmaximov commented on homework7/homework7/Enums/ConstEnum.swift
> +    static let topConstraint: CGFloat = 8
это не constraint, а константы для констрейнтов

2024-06-11 16:16 UTC, rmaximov commented on homework7/homework7/ImageTableViewCell.swift
> +    //    func configureView(with data: CarStruct) {
заккоментированный код

2024-06-11 16:16 UTC, rmaximov commented on homework7/homework7/Model/ImageLoader.swift
> +    private var completions: [URL: (UIImage?) -> Void] = [:]
очень интересный словарь _не комментарий к исправлению_

2024-06-11 16:16 UTC, rmaximov commented on homework7/homework7/Model/ImageLoader.swift
> +            print("Failed to download image from \(url): \(error.localizedDescription)")
от принтов лучше избавиться

2024-06-11 16:16 UTC, rmaximov commented on homework7/homework7/Model/ImageLoader.swift
> +        guard let data = try? Data(contentsOf: location) else { return }
може объединить с guard выше?

2024-06-11 16:16 UTC, rmaximov commented on homework7/homework7/Model/NetworkService.swift
> +    var results: [PhotoResult] { get }
зачем нам хранить и давать доступ к результату, если у тебя в fetchPhotos уже есть closure, который возвращает массив такой же?

2024-06-18 17:27 UTC, emmaderbe commented
Приношу свои извинения за долгий ответ на ревью! Закопалась в итоговом проекте

2024-06-18 17:29 UTC, rmaximov approved these changes

2024-06-18 17:30 UTC, merged